### ISSUE TITLE
What version of MySQL Workbench?

### ISSUE THREAD

**Issue by windowshopr** [brendanahart/MLBDailyProjections#2]
Hey!

Looking to get into your project. I downloaded MySQL Workbench 8 and it doesn't seem to have the "Table Import Wizard" option, you have to edit a newly created table, and select the import option from the Options tab below, however it still isn't working to allow me to import a CSV file. Eye roll. What version of MySQL workbench are you using for this? Thanks!

**Comment by brendanahart** [comment]
6.3 - fair warning - I haven't worked on this project for about 4 years and not sure if anything works but it's a good template if you want to make projections of your own
